### ISSUE TITLE
Having an issue with installation

### ISSUE THREAD

**Issue by leoc1f3r** [TroyAlford/react-jsx-parser#10]
When I am trying to install this package it shows me this error

`npm ERR! cb() never called!`

I tried all possible workarounds that I could find. Also tried with 5 different machines (Both Mac and Linux) and it is giving me the same issue on all of them.

**Comment by TroyAlford** [comment]
Trying it this morning (at least on OSX) it seems to install fine for me. Can you try again? (Maybe `npm` was having an issue or something?)

**Comment by leoc1f3r** [comment]
I am trying from past 2 days and having the same result. I tried installing other packages and those are working fine. This is the only package with which I am getting this error

**Comment by TroyAlford** [comment]
Hmm. I'm afraid there's not much I can do without being able to reproduce.
I'm sorry it's not working for you.

A little googling of the error tells me that `npm cache clean` may help.
Also - these threads on the npm repo seem related, though I don't see any
specific resolution to suggest:

   - https://github.com/npm/npm/issues/7014
   - https://github.com/npm/npm/issues/15344

One commenter suggests using `yarn` instead of `npm` (though that doesn't
feel like a satisfactory answer to me).

I'll leave the Issue open for now - please let me know if you find a
successful resolution.

**Comment by leoc1f3r** [comment]
I tried doing `npm clean cache`, I tried doing `npm upgrade`, and also tried it with `--verbose` flag. None seemed to work. Yarn is not a solution for me atleast. I will try finding something as I clearly don't understand the reason behind it. Other packages are not showing any issues with npm.

**Comment by TroyAlford** [comment]
Well nuts. :\ Yeah - definitely keep me updated. Happy to make a change if
there's something on this end, but at the moment - I don't see any
indication that the package itself has problems.

**Comment by leoc1f3r** [comment]
I tried again on 2 other colleagues machines with the same result. Both had different npm versions, so I don't think it is an issue with npm. But I cannot see similar problems with other packages to be honest. I am trying to find other workarounds at the moment.

**Comment by TroyAlford** [comment]
I did some more googling, and NPM issue 12281 indicates that this error may
indicate something wrong with tarballed dependencies. When I switch up my
configuration a bit, it appears that `yarn` chokes on the tarball from NPM.

I'll try republishing tonight - perhaps something with the tarball for
`0.0.12` became corrupted during the publication process. When I try the
same thing with `0.0.10` it works fine.

I'll try to push out another version tonight, and see if it helps things.
Thanks for the patience and the assistance!

**Comment by TroyAlford** [comment]
Sorry again for the delay. I just pushed `0.0.13` up to `npm` and verified that installing from tarball (at least with `yarn`) appears to be working correctly. This was the repro case that I was able to use before.

Can you please test and let me know if it's resolved your issue?

**Comment by leoc1f3r** [comment]
Awesome. This solved it. 👍 :) Closing the issue.

**Comment by leoc1f3r** [comment]
this.props.mychildren.map((child, key) => {
        return (
            <JsxParser
                components={[TextBox, Name]}
                jsx={child}
            />
        );
    })

Trying to do this. But it is giving me a warning. How do I solve it. I am already passing a unique key for each component.

**Comment by TroyAlford** [comment]
Well - the issue is probably that you're doing a loop, and returning multiple `JsxParser` elements, each of which needs a `key`. 

```
this.props.mychildren.map((child, key) => {
    return (
        <JsxParser key={key}
            components={[TextBox, Name]}
            jsx={child}
        />
    );
})
```

The above may solve it - though in this case, `key` is actually the index of the `mychildren` array which you're iterating over, and it's generally unadvised to use the `index` of the array as the key prop, as inserting an element in the array later on will result in confusing React.

Either way - I doubt that the problem is what's happening inside this lib. If you see evidence that it is, though, please open a new issue and give me a more comprehensive repro that I can take a look at. :)
