### ISSUE TITLE
Unable to build project.

### ISSUE THREAD

**Issue by CasanaT** [TroyAlford/react-jsx-parser#108]
Hello. Having some issues with this package. It works perfectly fine when running local in a development environment but when i build the project it crashes/not woking at all. Im getting the the error below in the console and nothing else is rendered in that component e.g the console.log in the constructur. If i remove the Jsx parser component the project works fine. Any idea what can be wrong?

```
 TypeError: Super expression must either be null or a function
    at individual-text-article.js:9
    at individual-text-article.js:9
    at Module.<anonymous> (individual-text-article.js:9)
    at a (individual-text-article.js:9)
    at e.exports (individual-text-article.js:9)
    at Object.<anonymous> (individual-text-article.js:9)
    at l (webpack-89179faa512dd01fbb62.js:1)
    at Object.<anonymous> (individual-text-article.js:9)
    at l (webpack-89179faa512dd01fbb62.js:1)
    at Module.<anonymous> (individual-text-article.js:9)

```
   **package.json**
```
 "react-jsx-parser": "^1.21.0",
  "react": "^16.8.0",
  "react-dom": "^16.8.0",
```

**Build script:** 
`"next build && next start -p 8081",`

**Main component**
```
import React, { Component } from 'react';
import JsxParser from 'react-jsx-parser';
import YoutubeInline from './YoutubeInline';

export default class IndividualTextArticle extends Component {

  constructor(props) {
    super(props);
    // eslint-disable-next-line no-console
    console.log('IndividualTextArticle constructor props', props);
  }
....More code

render(){
    return (
 <JsxParser
          onError={(e) => console.log('JsxParser Error: ', e)}
          showWarnings={true}
          components={{ YoutubeInline }}
          jsx={`<YoutubeInline videoId="O8wIJd7EHMs" />`}
   />
 )
}


```
**Rendered component**
```
import React from 'react';

const YoutubeInline = (props) => {
  // eslint-disable-next-line no-console
  console.log('YoutubeInline is rendered', props);

  return (
    <div className="col-12 col-md-10 mx-auto video-wrap xxs-mb-40 ">
      <iframe
        width="560"
        height="315"
        src={`https://www.youtube.com/embed/${props.videoId}`}
        frameBorder="0"
        allowFullScreen="allowFullScreen"
      />
    </div>
  );
};

export default YoutubeInline;

```

**next.config.js (if relevant)**

```
const withSass = require('@zeit/next-sass');
const nextEnv = require('next-env');
const dotenvLoad = require('dotenv-load');

dotenvLoad();

const withNextEnv = nextEnv();

module.exports = withNextEnv(
  withSass({
    webpack: function(config) {
      config.module.rules.push({
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            name: '[name].[ext]'
          }
        }
      });
      return config;
    }
  })
);
```

**Comment by CasanaT** [comment]
Seems to have something to do with minimising of the code? When I add this to my next.config.js it seems to work when building locally. 

config.optimization.minimizer = []; 
```

module.exports = withNextEnv(
  withSass({
    webpack: function(config) {
      config.optimization.minimizer = [];
      config.module.rules.push({
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            name: '[name].[ext]'
          }
        }
      });
      return config;
    }
  })
);
```

**Comment by TroyAlford** [comment]
Hmm. AFAIK, this project doesn't have any "strange" stuff that it's using which should require custom config - esp. if you aren't building from source. Based on your stack trace, this looks like an issue with your `super()` call in the `constructor`. What is it that leads you to believe it's this lib causing the issue?

FWIW - I have a `next.js` project which uses this component as well - and I don't recall having to do any special config in order to make it work. I've had to do plenty of manipulation of the `next.config.js` file in order to get _various_ things to work - but I don't recall any of them being `react-jsx-parser` related.

**Comment by CasanaT** [comment]
As it worked fine when I commented out the <JsxParser  /> component from the code it started working, so I just assumed it had something to do with this lib? But we manage to fix this by excluding some of the componentes from minifying in the next.config.js file. Instead of passing in an empty array as above as it omitted all minifiying this should omit the components instead

next.config.js
```

const TerserPlugin = require('terser-webpack-plugin');
module.exports = .... {
....
  config.optimization.minimizer = [
        new TerserPlugin({
          exclude: [
            /^ComponentA\.js(\?.*)?$/i,
            /^ComponentB\.js(\?.*)?$/i,
            /^ComponentC\.js(\?.*)?$/i
          ]
        })
      ];
...
}
```

**Comment by pavelradkovic** [comment]
I have similar problem.

```
react-jsx-parser.min.js:1 Uncaught TypeError: Super expression must either be null or a function
    at react-jsx-parser.min.js:1
    at react-jsx-parser.min.js:1
    at Module.<anonymous> (react-jsx-parser.min.js:1)
    at r (react-jsx-parser.min.js:1)
    at e.exports (react-jsx-parser.min.js:1)
    at Object.s0mw (react-jsx-parser.min.js:1)
    at r (bootstrap:19)
    at Object.2OHl (JsxParser.bs.js:8)
    at r (bootstrap:19)
    at Object.DW8a (ContentPageUtils.bs.js:5)
```

This happens only on production with minified version. I can build the project, but it happens in runtime. Problem is between 1.19.1 and 1.20.0. If I downgrade to 1.19, all works.

**Comment by CasanaT** [comment]
I started with 1.19 and got this error and then upgraded to 1.21.0 but same error. Tried different versions and still the same error. The only thing worked for me so far is the excluding in the config as above.

**Comment by TroyAlford** [comment]
@CasanaT - but you do _not_ need to exclude `react-jsx-parser` from the `Terser` plugin? Just the individual components you are attempting to use in it?

**Comment by CasanaT** [comment]
Yes, exaclty. Only my components as shown in my next.config.js. Thats pretty much all i did.

**Comment by TroyAlford** [comment]
Ok. My suspicion is that `Terser` is actually collapsing the _names_ of your components in some fashion, such that when the `JsxParser` attempts to apply the name `ComponentA`, for instance, it can't find one - because `Terser` has converted it to `A` or something similarly "terse."

Can you please give me an example of how you're applying the `components` prop?

**Comment by j0xhn** [comment]
Same issue is happening with me.  Thank you for this package, very useful and working perfectly before create-react-app builds project.  Steps to re-create:

clone  => https://github.com/johndangerstorey/hackthesnack
run      => `npm run build && serve -s build`
visit     => `localhost:5000` gives blank page with error `Uncaught TypeError: Super expression must either be null or a function`

**Comment by TroyAlford** [comment]
@johndangerstorey - I cloned your repo, upgraded back to `react-jsx-parser@1.21.0`, ran the build & serve - and it runs fine. :\

Are there other changes I need to make in order to recreate?

**Comment by TroyAlford** [comment]
I'm closing this issue, due to inactivity. If folks find further problems here, feel free to provide repos with reproduction instructions - but thusfar, I can't reproduce any of the above examples, and once I respond the folks who've reported it have stopped answering.

**Comment by CiroMzy** [comment]
Same issue happened to me.It works well in a development environment, but show the same error. I changed to 1.19.0 and it runs well.

**Comment by TroyAlford** [comment]
@CiroMzy - as mentioned with the others, this is likely that your minifier is changing the _names_ of the components.

In your source code, you may have `ComponentA` as the name of the component - but depending on how you transpile, this could be changed to `abc` (minification) or `__webpack_components_ComponentA_` (webpack) in the actual source code. Since we generally disable minification like this in development mode, you won't see the problem there - but when you turn on `NODE_ENV=production`, something in your toolchain decides is alterint the names.

This is usually transparent when you look at things in the browser, because modern tooling also produces sourcemaps - so when you load it up in Chrome or FireFox, you'll see your original source - not the minified version.

However, because the binding to `react-jsx-parser` happens at _runtime_, and it's _string_-based, this could cause you to wind up not having a match.

To fix this, you probably need to better control your imports, and, wherever possible, use _named_ imports - not _default_ imports.

In @johndangerstorey's case, he was doing the following:
```
import { Highlight } from '../components'
<JsxParser bindings={{ Highlight }} {...otherProps} />
```
but `Highlight` was created as:
```
// components/index.js
export { default as Highlight } from './Highlight'

// components/Highlight/index.js
const Highlight = styled.span`
  stuff here
`
export default Highlight
```

This means that when webpack picks it up, your component is actually named `default` - not `Highlight`. When you then re-export it, things get even weirder. When the compiler/minifier attempts to resolve this, webpack turns it into some crazy `__webpack_import_components_Highlight1_default_` sort of name, and it only _looks_ like the normal name in your code due to sourcemaps. This does _not_ happen when you're running in dev-mode, however, as noted above.

If, however, you were doing the following:
```
// components/Highlight/Highlight.js
export function Highlight({ prop: 'values' }) {
  return <div className="highlight">{etc}</div>
}

// file using JsxParser
import { Highlight } from './components/Highlight/Highlight'

<JsxParser bindings={{ Highlight }} />
```
This should work just fine. The difference is that you're using a named export - and that tells the build tools that the name is _load-bearing_. When you use `export default` it tells the build tools that the name is _arbitrary_ (or more to the point - that the name is `default`, and your import statement renames it).

This is the pattern you want to follow, using named exports. They also play better with TypeScript, which is an added bonus.

**Comment by jpodpro** [comment]
i'm using latest (1.23.0) and i'm having the same problem simply just by importing this lib and doing nothing else with it:

`import JsxParser from 'react-jsx-parser';`

i'm using create-react-app with default settings. this clearly has nothing to do with transpiling of components or bindings for me. note also that downgrading to 1.19.0 works properly. it feels pretty safe to say that something is broken after 1.19.0. this issue needs more thorough investigation.

package.json:
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@date-io/date-fns": "^1.3.11",
    "@material-ui/core": "^4.8.3",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/pickers": "^3.2.8",
    "axios": "^0.19.1",
    "canvas-toBlob": "^1.0.0",
    "chart.js": "^2.9.3",
    "date-fns": "^2.8.1",
    "env-path": "^1.0.7",
    "file-icon-vectors": "^1.0.0",
    "lodash.debounce": "^4.0.8",
    "notistack": "^0.9.7",
    "path-to-regexp": "^1.7.0",
    "react": "^16.11.0",
    "react-app-polyfill": "^1.0.5",
    "react-avatar-editor": "^11.0.6",
    "react-chartjs-2": "^2.8.0",
    "react-dom": "^16.11.0",
    "react-dropzone": "^10.2.2",
    "react-ga": "^2.7.0",
    "react-geocode": "^0.2.1",
    "react-jsx-parser": "^1.23.0",
    "react-material-ui-form-validator": "^2.0.10",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.0.1",
    "react-svg": "^11.0.16",
    "react-transition-group": "^4.3.0"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "plugin:cypress/recommended"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  },
  "devDependencies": {
    "cypress": "^4.5.0",
    "eslint-plugin-cypress": "^2.10.3"
  }
}
```

**Comment by TroyAlford** [comment]
That's great info - given that repro note, I'll see if I can reproduce this today.

**Comment by TroyAlford** [comment]
@jpodpro - I can't repro what you're describing locally or on codesandbox. Here's what I tried:

 - created a fresh CRA app
 - `yarn add react-jsx-parser`
 - modify `App.js` to use `JsxParser` to render everything
 - added a named component, and injected that into the App
    - tried as a named export
    - tried as a default export
 - ran it in development mode AND in production mode
 - repeated all of the above in CodeSandbox, which is essentially an online CRA tool.
    - https://codesandbox.io/s/react-jsx-parser-building-twygx?file=/src/App.js

I can't get the error to happen. :\

Can you please create a minimal repo in which this bug happens? I'd love to get to the bottom of it - but so far none of the examples above are things I can get to break on my side, simply by trying to follow a description, and the only thing close to a smoking gun which I can find is @CasanaT's scenario, in which it was clearly something about minifying component names.

**Comment by jpodpro** [comment]
i spent some time stripping down my project into basically nothing and i still get the error:
```
react-jsx-parser.min.js:3468 Uncaught TypeError: Super expression must either be null or a function
    at react-jsx-parser.min.js:3468
    at react-jsx-parser.min.js:3467
    at Module.<anonymous> (react-jsx-parser.min.js:3466)
    at n (react-jsx-parser.min.js:26)
    at e.exports (react-jsx-parser.min.js:62)
    at Object.<anonymous> (react-jsx-parser.min.js:16)
    at f ((index):1)
    at Module.21 (main.8ab2beb3.chunk.js:1)
    at f ((index):1)
    at Object.4 (serviceWorker.js:132)
```

this is the context in your minified code that is throwing the error:
```
    var j = s.Parser.extend(n()()),
        R = function (t) {
      !function (t, e) {
        if ("function" != typeof e && null !== e) throw new TypeError("Super expression must either be null or a function");
        t.prototype = Object.create(e && e.prototype, {
          constructor: {
            value: t,
            writable: !0,
            configurable: !0
          }
        }), e && P(t, e);
      }(s, t);
      var e,
          i = (e = s, function () {
        var t,
            i = O(e);

        if (L()) {
          var s = O(this).constructor;
          t = Reflect.construct(i, arguments, s);
        } else t = i.apply(this, arguments);

        return T(this, t);
      });
```

i have zipped up the simple project that is causing the error including the build artifacts, since it doesn't happen in development but only with a production build. 
[jsxparser-test.zip](https://github.com/TroyAlford/react-jsx-parser/files/4646473/jsxparser-test.zip)

note that i tested this in a windows and mac development environment and both resulted in the same error.

**Comment by TroyAlford** [comment]
Okay - I think I finally tracked this down. It looks like the issue is that the build is producing `umd`-formatted output, and CRA (and probably other build systems) are much more likely to work using `commonjs`. Something about the difference between the two formats appears to be what's breaking here, upon the way CRA minifies.

Since so many people use CRA for their React stuff, it is important that this lib support it OOTB - so I'm going to make this lib output both a `cjs` and a `umd` build, with the default being `cjs`. This should make the project code you uploaded work with no changes (tested locally to verify).

Thanks a ton for the repro! I would not have been able to track this down without it. :)

I'll add another comment shortly when I release the fix.

**Comment by TroyAlford** [comment]
This is now released as [v1.24.0](https://github.com/TroyAlford/react-jsx-parser/releases/tag/v1.24.0)

**Comment by viniciusfss** [comment]
I think this issue is back in version v1.28.

I noticed that the main file in the build is the umd version, as in the current package.json.

```
...
"main": "dist/umd/react-jsx-parser.min.js",
  "types": "dist/index.d.ts",
  "name": "react-jsx-parser",
  "repository": "TroyAlford/react-jsx-parser",
  "version": "1.28.1",
  "dependencies": {
    "@types/jsdom": "^16.2.4",
    "acorn": "^8.0.4",
    "acorn-jsx": "^5.3.1",
    "core-js": "^3.6.5"
  },
```

For using in my CRA project, I went back to v1.24.0 and it works fine, but I was wondering if there's any way of dynamically choosing the build version between `umd`, `cjs`, etc.

Cheers

**Comment by TroyAlford** [comment]
Yes - you should be able to use:
```ts
import JsxParser from 'react-jsx-parser/dist/cjs/react-jsx-parser.min.js'
```

By specifying the path, you should be able to load the `cjs` version instead of the default `umd` version
