### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by dawnerd** [TroyAlford/react-jsx-parser#112]
We have some content that's coming back that contains the following:

```html
<div class="embedded-content" data-template="readmore" data-amp-enabled="1"><script type="application/json">{"nid":"9337379","type":"post"}</script></div>
```

Ends up with this error: SyntaxError: Unexpected token (5:114)

Guessing it's tripping up on the script tag being a different type with json. 

Is there a way to have it skip it? (Even with the script tag blacklisted still happens)

**Comment by TroyAlford** [comment]
The issue, here, is that the above is not valid JSX. The JSX interpreter sees the `{` at the first character of the script content, and assumes it's a JSX binding. Even if you were to double the `{`'s, making them `{{` - I think you'd just get a different error, stating that an object is not a valid React object.

You can make this valid JSX, however, by wrapping it with backticks. So your code would become:
```
<script type="application/json">`{"nid":"9337379","type":"post"}`</script>
```

Better yet, however, would be to have whatever piece of code it is that fetches this string from the server pre-process it, removing all the `script` tags, and dealing with their content.

A naive approach to this, not knowing the rest of your application space, would be something like:
```
const html = await fetch('/get/the/data')
const parser = document.createElement('div')
parser.innerHTML = html

const bindings = Array.from(parser.querySelectorAll('script')).reduce((all, script) => {
  if (script.getAttribute('type') === 'application/json') {
    const json = JSON.parse(script.innerHTML)
    const type = json.type
    if (!all[type]) { all[type] = [] }
    all[type].push(json.nid)
  }
  script.remove()
}, {})

this.setState({ bindings, html: parser.innerHTML })
```
Then you could use these bindings as:
```
<JsxParser
  bindings={this.state.bindings}
  jsx={this.state.html}
/>
```

This allows your application to _safely_ deal with the `script` tags, rather than having the `JsxParser` attempt to do so, so you can safely handle your loading.

A second approach would be to write a _component_ which you let the `JsxParser` use, which is capable of summoning its own data - rather than getting it back, embedded as a `script`.

If those suggestions don't help, unfortunately, there's not much I can do. This lib explicitly does not, and will not, support `script` tags, or parsing their bodies, because it poses such a severe security risk - so unfortunately, if you want to use this lib, the best thing to do is not pass script tags to it at all.
