### ISSUE TITLE
React Native component's event handlers not working

### ISSUE THREAD

**Issue by kulkarnisaumitra98** [TroyAlford/react-jsx-parser#119]
I am trying to add onPress event on Text component, but it isnt working with React Native, It also doesnt work on Touchable Opacity.

**Comment by TroyAlford** [comment]
@kulkarnisaumitra98 I'm sorry to hear that. I've never used React Native for anything, and while I'm glad that this lib has been reported to work with it, I do not offer any official support for it.

That said - you may want to make sure you've properly set `blacklistedAttrs={[]}`, so that it isn't filtering out `on*` events from being bound. Also - it's impossible to reproduce a bug report without you listing _any_ code. If you'd be so kind as to link to a repository, or working reproduction, there are other folks who sometimes monitor these Issues, who do use React Native, who may be able to help?

**Comment by kulkarnisaumitra98** [comment]
Sorry for not being elaborate enough with the question.

heres the code snippet

```javascript
import React from 'react';
import JSXParser from 'react-jsx-parser';
import { StyleSheet, View } from 'react-native';


const string = '<Text onPress={handleOnPress}>Hello I am {foo}</Text>';

const JSX = () => (
  <View style={styles.container}>
    <JSXParser
      bindings={{
	foo: 'foo',
	handleOnPress: () => console.log('I Am Pressed'),
      }}
      jsx={
	string
      }
    />
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default JSX;
```

It seems like the parsing is actually working, Text, View etc, are being rendered which is great but the problem is with event handlers which dont get fired, I am using react-native-web.
My goal was to recieve a server side string as a component and inject it into the react native components. For react we have dangerouslySetInnerHTML attribute but for react-native there doesnt seem to be something similar.

**Comment by TroyAlford** [comment]
@kulkarnisaumitra98 by default, `on{Event}` props are filtered, to prevent exploits. In order to enable `on{Event}` bindings, you need to add one more prop to your `JsxParser`:
```
const JSX = () => (
  <View style={styles.container}>
    <JSXParser
      bindings={{
	foo: 'foo',
	handleOnPress: () => console.log('I Am Pressed'),
      }}
      blacklistedAttrs={[]} // this line should fix your issue
      jsx={string}
    />
  </View>
);
```

This is because the default value of `blacklistedAttrs` is `[/^on.+/i]`- which prevents both the React-style `onEvent` and the HTML-style `onevent` from being bound.

**Comment by kulkarnisaumitra98** [comment]
@TroyAlford thanks, I did ```blacklistedAttrs={[]}``` and it worked, also for anyone using it for react native web we would need to change the event handlers to the react JS event handlers to make it work, for eg.
```javascript

const string = '<Text onClick={handleOnPress}>HelloI am {foo}</Text>';

```

**Comment by TroyAlford** [comment]
Glad you were able to resolve it :)
