### ISSUE TITLE
Losing Focus on Rerendered Inputs

### ISSUE THREAD

**Issue by timkindberg** [TroyAlford/react-jsx-parser#120]
Hi Troy,

I'd mentioned this before but wanted to recreate the issue officially to see if you had any insights. If I can get this component working reliably it would help my team quite a bit as we'd be able to write JSX in our json strings instead of array tuples which are not as powerful.

The issue is, something is causing the input to lose focus when you type a character and I'm not able to determine what.

You can see the issue here: [JSXField Example](https://codesandbox.io/s/react-jsonschema-form-jsxfield-gltfk?file=/src/index.js)

It shows one of the examples working and one breaking.

The one that works:
- Isn't using any JSX, it's only using jsx expressions in brackets. The $.Name and $.Age are special bindings I've set up, those will output the form fields (plus label, error, helptext, etc). _That's actually something else that bugged me, I'd prefer if I could do `<$.Name />` but it was not working and maybe it's related to this same bug._
```
        { true && $.Name }
        { formData.Name && $.Age }
```

The one that breaks:
- Uses the `<Properties />` JSX component that I registered with the `components` prop. `<Properties />` renders all the form fields in the json schema properties. It works, but when you type into the field you lose focus. Then I'm also trying to print the value that you are typing in a div. So every time you update the form, I take the new form values and re-inject them back into the JSX parser so that you can use those values. (I realize this is probably at the root of the problem, but I feel like I should be allowed to change the bindings and components without losing focus)
```
        <div>{formData.Name}</div>
        <Properties />
```

Any help you could provide would be much appreciated, I'm also open to pairing on the issue if you have time.

**Comment by TroyAlford** [comment]
Hm. Yes - what you're doing seems reasonable. I suspect the issue is something to do with how keys are generated, internally, and how that interplays with the `react-json-schema` component.

https://codesandbox.io/s/jsxparser-disablekeygeneration-j8ew4 is a simpler example, which doesn't use `react-json-schema` - and you can clearly see the same focus-dropping if you comment out `disableKeyGeneration` in the `App.js` file.

This is because, internally, if you do not `disableKeyGeneration`, the parser recreates a `randomHash()` as the `key` for every `Element` and `JSXText` fragment, which forces them to re-render brand new components - which means, in your case, the browser throws away the `input` and creates a new one.

This is _valuable_ behavior when you're doing something like live-editing JSX in a rich editor, and having it live-update in a `JsxParser` to preview the results. It prevents `React`'s internals from treating `foo bar <b>baz</b> quux` and `foo <b>bar</b> <b>baz</b> quux` incorrectly (confusing the _new_ first `<b>` tag for being the 2nd one - which wouldn't actually matter in this contrived example, but _would_ matter if those were components with state).

In your case, however, you probably _never_ want this (unless you're live-editing JSX, with a preview, as mentioned above). So you can probably get away, safely, with applying the `disableKeyGeneration` prop. This is because in _your_ case, the overall JSX being rendered should be static in _organization_.

This, alone, however, is not sufficient to fix your issue - and where it gets lost, beyond that, _seems_ to be internal to how `react-json-schema` works. Unfortunately, while I've used that lib a bit in the past, I quickly decided it was overly complex for what I was after, and abandoned it - instead opting to build a trimmed down version for my company which was a little more laser-focused, and less infinitely configurable. So... I'm not much help for figuring out how it works. :\

**Comment by TroyAlford** [comment]
Oh - and in answer to your question, I'm totally open to pairing on it sometime. Shoot me an email, and we'll work it out.

**Comment by timkindberg** [comment]
Yes! I fixed it. It was a mix of how the two libraries played together and ultimately I was recreating the `components` too often. I mitigated this by only defining them once and using context to pass down the changing props that caused so many rerenders. So now it's going through context. Your insights and advice helped me isolate it thank you!

**Comment by TroyAlford** [comment]
Phenomenal! I'm so glad to hear that, @timkindberg. :) I hope the library continues to help you and your team. I always appreciate your Issues and thoughtful commentary.
