### ISSUE TITLE
Allow components to be a mapping

### ISSUE THREAD

**Issue by developit** [TroyAlford/react-jsx-parser#13]
Having `components` be an Array relies on those components having a `.name` property, which will be mangled in any production setup (eg: uglify). Some people define a `displayName` property on the constructor, which could make that technique more reliable.

I'd likely suggest it might be worth supporting the existing Array format alongside passing `components` directly as an object.  Here's an example of where the object is very useful:

```js
<JsxParser components={{
  // these classes wouldn't likely be named "A" or "IMG"
  a: Link,
  img: LazyImage
}} />
```

**Comment by TroyAlford** [comment]
So - I'm imagining that the array version would check for a `.name` or `.displayName` case-sensitive match - and the object version would make a case-sensitive comparison against the object key.

I'm not 100% on the case-sensitivity part - but my thinking is that it allows someone to process normal `<a>` tags as they wish, or `<A>` tags with a special handler. Again - not sure this is the best option, though. What do you think?

**Comment by timsuchanek** [comment]
Do you want to support both the array and the object api? If it's just the object API, I quickly implement it

**Comment by TroyAlford** [comment]
I was envisioning doing both - but the object API is probably the more important future-facing version. The array API would be for backward compatibility, primarily.

**Comment by TroyAlford** [comment]
I put in PR #14 in order to address this - take a look, and let me know what you think.

I got through most of the implementation which would have allowed this to also support the Array API going forward - but it started to be more code than I wanted, ugly to follow, and seemed over-complicated for very little gain.

This change, for most folks, will allow them to simply change from saying: `components={[ A, B, C ]}` to saying `components={{ A, B, C }}` (`[]` to `{}`). It is, however, a breaking change - so I think it requires a major version bump.

**Comment by timsuchanek** [comment]
After trying it out in a production build now, I just can agree on what @developit said, the names will be pruned and the components don't work anymore. So I think it makes sense to only support the object api in the future. It's also even less code in the implementation than with the array because you just can leave the `reduce` away

**Comment by TroyAlford** [comment]
Great point on eliminating the `.reduce` entirely. I just updated #14 based on that. Going to merge today, and release v1.0.0 to npm
