### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by aridclown** [TroyAlford/react-jsx-parser#142]
Hi, is it something the react-jsx-parser component thinks of having in the future?

That's a very nice feature and would enhance the parser to be more complete.

**Comment by TroyAlford** [comment]
Hi @diogosouza - thanks for your interest in the lib! Sorry that I didn't see this until just now!

In terms of the feature - I'm unclear as to what exactly you have in mind? The `JsxParser` component currently just takes in JSX, parses it, converts it to rendered React, and renders it to the screen. Where would you envision a copy to clipboard button going? And what, exactly would it copy?

**Comment by aridclown** [comment]
Hi @TroyAlford, thanks for answering.

I'm sorry, I should've posted a pic to exemplify, I meant something like this:

![image](https://user-images.githubusercontent.com/764655/90981041-3006c980-e535-11ea-8e1f-81fbe65e4213.png)

A button to allow users to, optionally, copy/paste the code to somewhere else.

**Comment by TroyAlford** [comment]
@diogosouza - I think either I'm fundamentally misunderstanding what you're envisioning, or you're fundamentally misunderstanding what this lib does. :) This lib does not show source code - it renders JSX into React components, then passes them to React to turn them into HTML.

If you opt to attach it to a source-code renderer, so that you can live-type JSX, that rendering is probably what you would want to add a "Copy" button to. Unless you're wanting this lib to render a `Copy` button which would copy the currently rendered HTML to your clipboard, perhaps?

If that last thing is the case, doing so is outside the scope of what this component is for - though I'd welcome you to use this lib inside a component of your own, which would do what you're requesting. :)
