### ISSUE TITLE
JSX Curly Braces Disable?

### ISSUE THREAD

**Issue by mustafa519** [TroyAlford/react-jsx-parser#146]
Hello,

Is there a way to disable the inline curly brackets support? I'm generating complex output that to convert to JSX and i'm having problem with them. Like [KaTeX](https://katex.org) or code blocks. Already i only use this library to convert html to JSX without inline variable support.

I think there should be a support that we can disable inline curly braces support.

Thank you for the good lib.

**Comment by TroyAlford** [comment]
I'm afraid not at the moment. The parsing is done via AcornJSX, and I don't know that we can easily distinguish this type of bracketized value from regular HTML expressions. I suppose all HTML expressions would simply be strings?

Can you give me an example of a scenario that's failing/giving you trouble? So I can understand the use-case?

**Comment by mustafa519** [comment]
I've created simple markdown to html parser. And i'm putting the output to JSX parser. I've been fine until now. But when i have to use curly braces then problems came. It has lots of supports like Code Highlighting, KaTeX(Latex), Diagrams(mermaid).

Most of them uses curly braces syntax inside of it. It's really hard to separate that inside of the component even it has a lot of children component.


## An example for Code Highlighting:
![image](https://user-images.githubusercontent.com/4794086/91328312-6bbcc000-e7cf-11ea-83fb-6ca021e50440.png)

As you can see, I can encode in backend before send the output but then i have to decode inside of all children component. Also to separate and decode would cause to decrease too much performance.

Could you suggest something that i can fix the issue by myself? Or any idea for the solution?

---

**Edit:** Also it doesn't work something like `\{ ... \}`.

---

**Edit 2:** I just have an idea and it works for now. 

```php
$content = preg_replace('/([\{\}])/s', '{\'$1\'}', $content);
```

**Comment by TroyAlford** [comment]
Glad you found a working solution. :) The reason this happens, I believe, is due to `react` making "safe" anything you output inside your components. In general, the way I usually bypass this is by using template-strings for code that shouldn't get munged.
```
<style>{`
  div.my-class { width: 100%; }
`}</style>
```
React should inject this form of content without altering it.

The other standard approach is to use `__dangerouslySetInnerHTML` - but I don't believe that will work with this lib, to begin with - and it probably wouldn't be easy for your code to implement, either.

Either way - sounds like you already have a solution, so I'm closing this issue for now.
