### ISSUE TITLE
Request: Allow bindings not specified in JSX string

### ISSUE THREAD

**Issue by GemKosan** [TroyAlford/react-jsx-parser#147]
@TroyAlford, Please let me know if this is currently possible. If not, I'd love to see this added in a future release!

I am separating content/layout data into a separate JSX file. I want to be able to exclude the component bindings from this file, as they are irrelevant to the data layer of my SPA. Is there a way to pass bindings to the JsxParser component without them also being in the jsx string?

e.g. for the string below, I'd like to eliminate the attributes for myHandler, since this component will _always_ use this handler:

`
<MyComponent name={"comp1"} value={'a'} myHandler={handleEvent} />
<MyComponent name={"comp2"} value={'b'} myHandler={handleEvent} />
<MyComponent name={"comp3"} value={'c'} myHandler={handleEvent} />
...
`

Thanks,
  Gem

**Comment by TroyAlford** [comment]
@GemKosan - my suggestion, for doing this, would be to use the Context API to create this binding, rather than passing the handler as props, since, as you say, it will always be used.

Something like this:
```
const MyContext = React.createContext()

class MyComponent extends React.Component {
  static contextType = MyContext
 
  render = () => <button onClick={this.context.eventHandler}>Button</button>
}

class MyWrapperComponent extends React.Component {
  handleEvent = (event) => {
    /* actual event handler */
  }

  render = () => {
    return (
      <MyContext.Provider value={{ eventHandler: this.handleEvent }}>
        <JsxParser components={{ MyComponent }} jsx={`<MyComponent name="A" value="A" />`} />
      </MyContext.Provider>
    )
  }
}
```

Since you know the event binding is going to be static - you can simply supply the handler in the context. By putting the `JsxParser` inside the context provider, you're then ensuring that the strongly typed `MyComponent` class, which is looking for it, can successfully bind to it.

No need for special `JsxParser` logic, here - this is just built-in React stuff. :)
