### ISSUE TITLE
Components are re-constructed every render

### ISSUE THREAD

**Issue by GemKosan** [TroyAlford/react-jsx-parser#148]
Hi @TroyAlford,

I just discovered that my components from the JSX string are being re-constructed every time the JsxParser is re-rendered. Is this intentional? 

My expectation is that any existing JSX string components would simply re-render. I didn't see it discussed in your docs, and this is leading to some interesting bugs in my code.

ps: I believe this is related to your generation of unique keys, as the issue is only reproducible when disableKeyGeneration is defaulted to false.

**Comment by TroyAlford** [comment]
Yes - which setting you want depends on your use-case. As you mention, `disableKeyGeneration` may be appropriate for your situation. Auto-generated keys will generally force all components to be re-instantiated and thus re-rendered from scratch (discarding any state) whenever the JSX changes. For some scenarios, this is fine/good (such as when you're live-editing HTML with embedded non-stateful JSX components) - but in others, it's breaking (such as when you're rendering stateful components, as you may be).

**Comment by TroyAlford** [comment]
Incidentally - I think you're right that this should be better called out / documented in the README. I'll leave this issue open, for now, as a reminder to do that - though I'm also open to a PR, if you've got the time. If not, I'll try to get to it soon(ish).

**Comment by GemKosan** [comment]
Good to know. Thanks for the rapid responses to both of my issues.

**Comment by GemKosan** [comment]
Hey @TroyAlford, I just noticed something you said: 

> "re-rendered from scratch (discarding any state) **whenever the JSX changes**"

Did you mean whenever the **state** changes?
My jsx string is going into a private member variable (this.pageData) on the top-level App component as is **not** part of that component's state. It is being set only once from the App component's componentDidMount, and never changes.

So, either I'm misunderstanding you or there's a bug in my code causing the jsx to change (entirely possible). 
Please clarify.

**Note:** Although my jsx doesn't update after mount, the rendered component tree **will change** depending on a pageNumber  value in the App state.

**Comment by TroyAlford** [comment]
@GemKosan - sorry for the delayed response, I missed this.

To clarify - anything that causes the `JsxParser` to re-render, with `autoGeneratedKeys` turned on, will cause everything inside the parser to also be re-rendered. This is because, internally, each element now gets a new `key` on every render. So - if your parent component, which contains a `JsxParser`, changes its state - causing the parser to re-render, you are likely to blow away the state of any children which the parser has rendered.

By turning _off_ the `autoGeneratedKeys`, you allow React to handle the keys. This means the keys will be consistently applied based on the _order_ of the elements being rendered.

To clarify:
With `autoGeneratedKeys`, the JSX `<div>Foo</div>` will wind up as something equivalent to `React.createElement('div', { key: RANDOM_HASH })`. With the `autoGeneratedKeys` disabled, it will be `React.createElement('div', { key: 0 })` - because it's the first element.

On the subsequent load, you'll get a _different_ random hash when enabled - but you'll still get 0 if disabled. This is because React, by default, issues keys to children based on the order in which it sees them. The random keys functionality, conversely, randomizes the keys - ensuring a fresh generation of instances on every render.
