### ISSUE TITLE
input onchange 给父组件setSate 后输入框会失去焦点,

### ISSUE THREAD

**Issue by lsai2270** [TroyAlford/react-jsx-parser#176]
input onchange 给父组件setSate 后输入框会失去焦点,
应该是重新render导致的

**Comment by TroyAlford** [comment]
@lsai2270 if I understand correctly (Google translate is not perfect), I believe you are losing focus in a text box as the JSX changes. To solve this, you probably need to use the props to generate/not generate keys to the opposite setting from what you are using.

The issue is in how React resolves children and changes. If the keys aren't set and reapplied correctly, you wind up with a new text box, rather than a rerender of the existing one, and the new one doesn't have focus.

**Comment by lsai2270** [comment]
> @lsai2270 if I understand correctly (Google translate is not perfect), I believe you are losing focus in a text box as the JSX changes. To solve this, you probably need to use the props to generate/not generate keys to the opposite setting from what you are using.
> 
> The issue is in how React resolves children and changes. If the keys aren't set and reapplied correctly, you wind up with a new text box, rather than a rerender of the existing one, and the new one doesn't have focus.

Thank you very much for your reply, I tried to solve it with props keys, but it didn't work
![image](https://user-images.githubusercontent.com/32258110/106836730-ac046080-66d4-11eb-8ab8-33e90a84d410.png)
Do you have any other solutions?

**Comment by TroyAlford** [comment]
Unfortunately, not really :/ React simply cant always tell how to
reconstruct the same elements, depending on what changes in the text. If
you are actually typing in jsx and letting the editor rerender in real
time, certain edits are simply going to break the parser and cause a full
rerender.

This is especially true if you edit text such that your changes briefly
make the JSX invalid. In this case, there is no clean way for React to
recover.

My primary use case is that I use the component to drive my wiki site,
enriched with React components. All of the JSX editing, though, is done
either with TinyMCE or Ace Editor. In both cases, the JsxParser is off
screen while the editing happens. If that's feasible for you, it might be
an option?
