### ISSUE TITLE
Is there a way to handle special characters that would normally be processed by the parser?

### ISSUE THREAD

**Issue by Trevash** [TroyAlford/react-jsx-parser#177]
I came across an issue where the text input by a user included special characters such as these: `[] {} \ /`. This was causing the JsxParser to error out since it thought the input was invalid. Is there any way to tell the parser to ignore certain characters?

**Comment by TroyAlford** [comment]
Can you please give me an example of the JSX that's causing a problem?

**Comment by Trevash** [comment]
Something like this: `<Text><3 >:| () [] :/\ //\\</Text>` While creating an example for you, I noticed that the actual issue was the `<` and `>` characters Not the original characters that the error said were causing it. I assume that is because they are processed as opening and closing brackets for JSX components. If I stripped them out of the message, it parsed it fine. Is that the only way to handle them in the future? Is there a way to tell the JSX parser to ignore angle brackets internal to the message, within the component they are rendered in?

**Comment by TroyAlford** [comment]
Unfortunately, the parser cannot really distinguish between > and < which
are control characters vs those which are not. Jsx is simply less forgiving
a spec than html is in this way, and the Acorn parser parses as JSX.

One potential option (this is what I do) is to encode the non-control angle
brackets as &lt; &gt;. The parser should interpret those correctly as text
instead of control characters, and render them accordingly.

**Comment by Trevash** [comment]
Fantastic, that works perfectly! Thanks for the tip
