### ISSUE TITLE
for loop

### ISSUE THREAD

**Issue by DamianoNaraku** [TroyAlford/react-jsx-parser#190]
In react, looping is done through the Array.map function wich requires a function declaration as parameter.
But on this component function declaration inside jsx expression is forbidden for security, this makes apparently impossible to loop an array, and the following example code is unachievable.
`<><h1>colors:</h1><ul>{colors.map( (color) => <li>color: {color}</li>)}</ul></>`

I'd like to know if there is a way to circumvent this, but the ideal option would a solution that doesn't force tricks and changes in templates.

So i request an option to allow declaration of functions inside expressions dropping security.
Or another partial solution could be only allowing functions which have nothing else but a jsx expression and eventually a return (because they cannot pose a security threat).

Thank you for your work.

**Comment by TroyAlford** [comment]
Hey @DamianoNaraku - thanks for your interest in the lib!

#114 is open, and has been for a long time, as a placeholder for this type of functionality. The issue is that it is non-obvious what the best way is to implement such a function in a secure way. It has been discussed in #172, #185, and various other tickets as well, over time - but no resolution thusfar.

There are basically 2 approaches feasible:

1. parse the code inside the function, essentially transpiling it, or
2. `eval` the function, throwing security to the wind entirely

There are, of course, variants of both, as well.

The problem with 1 is that this would essentially require us to implement a full parser for the rest of JavaScript. You'd then need to make decisions about which syntax to support, and how far backward to transpile them. This is the territory of Babel, and doing it at run-time would both be a huge bloat to this lib, which is already larger than I'd like, and also an Endless Quagmire Of Configuration™.

If we opted to only support ES5 (or basic ES6, ala arrow functions) we would continue to get tickets like this one, into the future, asking for more and more specific language support.

The problem with 2 is that I fundamentally refuse to implement such a blatant OWASP violation in an open-source project. Simply taking the source code of someone's arrow function and `eval`ing it would inevitably lead to a malicious attack, such as a user uploading a JSX comment to a website which contained an arbitrary function that then gets executed AS the user who views it rendered on every page view.

Not only is that _extremely likely_ to happen if this lib supports the feature, 99% of the time it's unnecessary.

An honorable mention (and the only likely version this lib will ever receive) is essentially a 1a - in which we support a _very_ limited set of features, which would essentially offer:

 - built-in methods (such as `[].prototype.map`)
 - arrow functions which are _only_ a return statement

```ts
foo => <li>{foo}</li> // allowed!
foo => <li>{foo + 1}</li> // allowed!
foo => { const bar = foo + 1; return <li>{bar}</li> } // nope!
```

This last version, 1a, is what #114 is open to represent, and a further PR is definitely welcome if you'd like to help contribute it. In the meantime, the standard path for this feature is to implement something like the following:

```ts
<JsxParser
  bindings={{
    foos: [/* some array of items */],
    renderFoo: foo => <li>{foo}</li>,
  }}
  jsx={`
    <FooList items={foos} renderer={renderFoo} />
  `}
/>
```

**Comment by DamianoNaraku** [comment]
Your last code could be a valid solution if the renderer expression `foo => <li>{foo}</li>` is known and processed at transpile time.
But if the rendering template is received from a json or by some other dynamical means as a string, i still don't see a way to compute and render it correctly at run-time, wich should be the main reason for using this library.

Maybe i misunderstood, is there a way to dinamically iterate an array as a list of elements outside traspilation time?
If i receive from server the raw **string** `"<li>{foo}</li>"`, can i render it multiple time for each element inside a foos array?

**Comment by TroyAlford** [comment]
@DamianoNaraku the primary use-case for this lib is basically to use as a dynamic templating lib, or a way to render HTML-like JSX with embedded components in it, not to execute arbitrary code in the browser, which would constitute a major security problem and centrally open the door to a number of OWASP violations.

The bindings and components props give you a way to create helper utilities, exposed to those templates, which your end-users can then use.

So - if you want your users to be able to write `<a href="/foo">Foo!</a>` but actually have that rendered by a `react-router` `Link` element, for instance, you can easily do so. Now the user writes familiar HTML, but you get the power of React rendering elements as a component.

Similarly, if you want your user to be able to use `MyComponent`, they can now do `<MyComponent prop={{ foo: 'bar' }} />` and have it work, because you provided it in the `components` binding.

The whole point is that you take this level of control at _build_ time, and _not_ at design time - because at build time you are making safe, well-tested functions available. At design time, if the user is able to provide their own functions, they can do _anything_ javascript can do - but they can now do it within the context of your React code, as the user who's authenticated, etc. - and worse - they can (likely) push it to your server and get it to execute in the context of _other_ users who load the same template.

If you want your users to be able to render more generic elements, you have some options by being creative with React components. To create the color list more dynamically, as in your original example, for instance:

```ts
const Renderers = {
  Color = (color: string) => <>color: {color}</>,
  Default = (value: string) => <>{String(value)}</>,
}

const UL = ({
  listItems = [],
  type = 'Default',
} = {}) => {
  const LI = Renderers[type] ?? Renderers.Default
  return <ul>{listItems.map((item, index) => <li key={index}>{LI(item)}</li>)}</ul>
}

<JsxParser
  bindings={{ colors: ['red', 'blue', 'green'] }}
  components={{ color: Color, ul: UL }}
  jsx={`<ul listItems={colors} type="Color" />`}
/>
```
