### ISSUE TITLE
Use .map() inside jsx

### ISSUE THREAD

**Issue by stephen-golban** [TroyAlford/react-jsx-parser#204]
Hey, I absolutely love this package, It would help me a ton if there would be a way to use the map inside the jsx. 
Something like this:
import JsxParser from "react-jsx-parser";

export default function Builder() {
  const a = `
              <>
                {data.map((el, i) => (
                  <div key={i}>{el}</div>
                ))}
              </>
             `;
  return <JsxParser bindings={{ data: [1, 2] }} jsx={a} />;
}

I want to render a div based on the "data" binding, is something like that possible?

**Comment by TroyAlford** [comment]
Hey Stef -
First off, thanks for the kind words. I'm glad the package is helping you!

Allowing the JSX to actually contain a dynamic `.map()` function is a feature the package does not support, no - both because that would basically mean implementing a full javascript interpreter (or using `eval` or similar) - and it's a pretty dangerous thing to let users stick dynamic code in a database and execute it at runtime.

That said, you can do something like this:
```tsx
<JsxParser
  bindings={{
    data: ['a', 'b', 'c'],
    render: el => <div key={el}>{el}</div>,
  }}
  jsx={`<>{data.map(render)}</>`}
/>
```

This way, the renderer function is something you've provided - and `data.map(render)` simply uses the bound `render` function in order to output the element itself.

**Comment by hw-a** [comment]
oh thanks for the tips! 

look like map's para just got parsed  into `ArrowFunctionExpression` with params and body containing `BlockStatement->ReturnStatement->JSXElement` so alternatively we can parse-evaluate that JSXElement with map under a new binding i.e. per list's child!

**Comment by hw-a** [comment]
I think what's cool about this lib is that it's already sort of like an interpreter! so I guess if anyone really needs it, just have to implement nested bindings as the enviroment

**Comment by TroyAlford** [comment]
yep, exactly. :) glad it's working for you!
