### ISSUE TITLE
There is no way to add react's js code and other react things?

### ISSUE THREAD

**Issue by hkmsadek** [TroyAlford/react-jsx-parser#227]
How can we add js code considering the security is not an issue?

**Comment by hkmsadek** [comment]
Also logical expression doesn't render properly

**Comment by TroyAlford** [comment]
I assume, from this question, that you are referencing the use-case that you opened a separate issue for.

To answer the above, however:
> How can we add js code considering the security is not an issue?

You cannot, because this lib does not support on-the-fly parsing and execution of complex JS code baked into JSX templates. Supporting it in the future would be a major change, and is not currently on a roadmap of any kind.

> Also logical expression doesn't render properly

There are numerous unit tests and other examples which demonstrate logical expressions working within the lib. Without a code example, that statement is non-actionable on my end. If you would like to submit another code example, showing what's broken - please open a new issue for it.
