### ISSUE TITLE
JsxParser components shows blank when loading a little complex code from a server

### ISSUE THREAD

**Issue by hkmsadek** [TroyAlford/react-jsx-parser#228]
Ok so I am getting a blank component with no error at the console. Here is the code I am loading from server 

```
"<ul>
          {
            items.map( (item, index) => {
                return (
                  <>
                    <li key={index}> City is : {item.city}</li>
                    {
                      item.city == 'Lodon' ? 
                      <div>
                        <h1>This is not london city and it is {item.city}</h1>
                      </div> : 
                      <div>
                        <h1>Yes! This is london city and you can remove it: {item.city}</h1>
                      </div>

                    }
                  </>
                )
            })
          }
         </ul>"
```
I am running it like this 
```
 <JsxParser
          bindings={{items}}
          jsx={data.html} />
```

and my items are
```
  const [items, setItems] = React.useState([
    {city: 'Tokyo', country: 'Japan'},
    {city: 'New York', country: 'USA'},
    {city: 'London', country: 'UK'},
    
   
  ])
```

**Comment by TroyAlford** [comment]
We do not support dynamic functions inside JSX, as is stated clearly in the README and in many other issues. The only kind of `.map()` type interpretation that is supported is simple functions whose only body is a `return`. Examples would include things like:
```ts
<div>{users.map(user => user.name)}</div>
// or
<div>{users.map(function(user) { return user.name })}</div>
```

These types of functions pose little trouble for the on-the-fly interpreter, do not have to be `eval`'d, and bear very little security risk (because the above assumes `users` is one of your `bindings`, and if you made it available to the parser, you presumably _intended_ for it to be usable within the JSX parsing).
