### ISSUE TITLE
in react native hit this  Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by kaialsh705** [TroyAlford/react-jsx-parser#229]
function App() {
  let stringJsx = `<View> <Text style={{color:'red'}}>hello pppp</Text> </View>`;
 return (
    <View style={styles.app}>
      <JsxParser jsx={stringJsx}/>
    </View>
  );
}

![Screenshot 2022-04-01 at 12 04 59 PM](https://user-images.githubusercontent.com/59761075/161208431-6ce37281-fa6c-45e2-82c7-bef2da55eadc.png)

**Comment by TroyAlford** [comment]
You also may need to create a `components={{ Text, View }}` type prop. I'm not sure. Otherwise, the lib probably does not know what kind of component `<Text />` is. Under the hood, the lib actually takes any `PascalCased` tag and attempts to render it by mapping it to one of the `components` bindings. If it doesn't find one, it renders it as an unknown - which is probably what your error is complaining about.

That said, I do not use React Native, nor do I have any good way to provide support for it. My guess is that this is something to do with how you've set things up, however, as other folks have commented previously that Native works well with this lib.
