### ISSUE TITLE
When parent component rerenders JsxParser unmount previous inner components

### ISSUE THREAD

**Issue by AntonitoMt** [TroyAlford/react-jsx-parser#253]
If I have, for example, a form with a component JsxParser containing other components, when the form rerenders I see the components created into JsxParser unmount themselves and mount again.  Could it be avoided?

**Comment by TroyAlford** [comment]
Unfortunately, it's not very avoidable. When the parser runs over the `string` you've passed in, it has to break the JSX into an AST representation, then iterate over it to recreate everything and re-bind it. Internally, `react` takes each node that it binds and assigns it a `key` - automatically, unless you specify the key yourself - and that's what bites you.

Imagine you have a form that changes from:
```tsx
const jsx = `
<TextBox name="givenName" />
<TextBox name="familyName" />
`
```
to 
```tsx
const jsx = `
foo
<TextBox name="givenName" />
<TextBox name="familyName" />
`
```

The difference in the AST is huge. The biggest problem, though, is that the first string, `foo`, becomes its own node. Now, instead of `react` automatically assigning `key={1}` and `key={2}` to the `TextBox` elements, it automatically assigns `key={2}` and `key={3}` to them, and it blows things up. (this may not be exactly what the keys become, but the underlying problem is the same).

To control for this, you could add `key="value"` entries on each form element. In that case, you _may_ be able to control for what `react` will do to the underlying components and their re-renders.

Example:
```tsx
<TextBox key="givenName" name="givenName" />
<TextBox key="familyName" name="familyName" />
```

You may _also_ try setting `disableKeyGeneration={true}` on the `<JsxParser />` and see if that helps - or if a combination of these things does.

Let me know if you find a good workaround!

**Comment by TroyAlford** [comment]
[Here's an example](https://codesandbox.io/s/react-jsx-parser-playground-forked-6tc345?file=/src/index.js) demonstrating that setting the `key` within the form elements to something that doesn't change works.

**Comment by AntonitoMt** [comment]
Thanks for the explanation, TroyAlford. It was a great help to me. I preferred to activate the disableKeyGeneration prop, and for the moment it is satisfactory for what I need.

I had already tried, as an alternative, including the form itself within the Jsx string.

Thanks again and congratulations for such an interesting and efficient library.
