### ISSUE TITLE
Props in HTML Content

### ISSUE THREAD

**Issue by jbolda** [TroyAlford/react-jsx-parser#30]
I am trying to inject a value into `{this.props.test}` and it returns empty/blank. See the following snippet.
```javascript
<JsxParser
  bindings={{test: 'this is a test'}}
  jsx={'<h1>test</h1><p>seriously {this.props.test}</p>'} />
```

Am I misunderstanding or this is out of the scope of this project?

I was expecting output similar to the following.
```html
<h1>test</h1>
<p>seriously this is a test</p>
```
But I get:
```html
<h1>test</h1>
<p>seriously </p>
```

Thanks for your attention!

**Comment by TroyAlford** [comment]
Yes, I think you're misunderstanding how it works, a bit. :)

In the snippet you posted, above, `this` refers to whatever scope you are rendering the `<JsxParser ... />` inside of. I suspect that element has no `test` prop - and therefore, you are getting an empty string to be rendered.

To accomplish what you're expecting (or at least, something similar) - you'd need to do something like:
```
const Child = (props) => (<p>seriously {props.test}</p>)
```
Now, in your component, you can use:
```
<JsxParser
  bindings={{ test: 'this is a test' }}
  components={{ Child }}
  jsx={'<h1>test</h1><Child />'}
/>
```
When the Parser renders the `jsx`, it will first render the `h1` element, then it will render the `Child` component (which it understands, because you bound it to the `components` prop). When it renders `Child`, it will pass the `bindings` as props - and `Child` will therefore have a `test` prop.

Does that make sense?

**Comment by jbolda** [comment]
Ah! It wasn't clear to me that it _had_ to be within a component. Your response and taking a look at your tests was enough to get me where I was going with it. Thanks!
