### ISSUE TITLE
Key Warning

### ISSUE THREAD

**Issue by camdagr8** [TroyAlford/react-jsx-parser#44]
I'm getting the following warning:

```
Each child in an array or iterator should have a unique "key" prop. 
Check the render method of `JsxParser`. See https://fb.me/react-warning-keys for more information.
    in React.Fragment...
```

**Comment by TroyAlford** [comment]
@camdagr8 - yes - I need to auto-compute the keys in order to silence that warning in development. If you compile your project with `NODE_ENV=production`, it silences all of the warnings, in the meantime.

I'm going to mark this as a feature request. I think it should be handled by modifying the `parseChildren` method to apply a `key` prop if the child doesn't have one specified - and just auto-compute it based on the child's index. Given that I think most people are using this as an enhanced HTML parser (certainly what I'm using it for) - I can't think of a more performant mechanism for generating safe keys.

**Comment by camdagr8** [comment]
That sounds good. 
I gave it a try myself, but it still gave me the warning. 
I tried to do it on `this.ParsedChildren` in `render()` by mapping each child with a keyed `<Fragment>`

**Comment by camdagr8** [comment]
@TroyAlford any idea when this will be implemented?

**Comment by TroyAlford** [comment]
I'm going to take a stab at it now, and see if I can find a workaround.

**Comment by TroyAlford** [comment]
Neat... so - it appears that this was occurring when the element is of type `JSXText`. I've fixed it by making sure the `<Fragment />` which wraps the text has a unique `key` assigned to it, as well.

Example of what was breaking:
```
<b>Title</b> <span>Description</span>
            ^ this space gets rendered as a fragment, and needs a key
```

**Comment by camdagr8** [comment]
Nice! All is good.. Thanks @TroyAlford!
