### ISSUE TITLE
Issues with curly brackets

### ISSUE THREAD

**Issue by maddox** [TroyAlford/react-jsx-parser#47]
I'm seeing some weird effects when attempting to render a string that has a curly bracket in it. When attempting to render some code blocks, if I have a curly bracket that opens without closing on the same line, nothing will render. It's super weird.

Am I doing something wrong here?

## Examples

    <code>system {}</code>

Renders fine.

    <code>system {</code>

Does not render at all.

**Comment by TroyAlford** [comment]
Hmm - I bet the JSX parser is interpreting it as an injected variable and
erroring out because it's not a valid statement contained within.

In JSX, that example looks like you are injecting a variable, and then
passing the value as a malformed JSX element declaration.

I wonder how React handles that, in the same situation...

If it's feasible for your situation, you can probably work around it by
passing the contents of your code block as a binding.

```
<JsxParser
  bindings={{codeBlock}}
  jsx="<code children={codeBlock} />"
/>
```

If that doesn't work, a custom element should.

```
const Code = ({ text }) => (
  <code dangerouslySetHtml={{ _html: text }} />
)

<JsxParser
  bindings={{codeBlock}}
  components={{ Code }}
  jsx="<Code code={codeBlock} />"
/>
```

(I'm on my phone, so please forgive if these examples aren't perfect)

**Comment by maddox** [comment]
Well, but it also still borks on something like this...

```
<code>
window.setup = () => {
  // pre-load sound
  sound = loadSound('https://files.tttiny.com/production/users/jon/assets/r2d2.mp3');

  // create your canvas
  createCanvas(300, 300)

  // draw a background with a color
  background("cornflowerblue")

  // write text
  fill('blue')
  textSize(32)
  textAlign(CENTER)
  text("Click for R2-D2", 0, 10, 300, 300)
}
</code>
```
...where the ending bracket is there, but on another line. It's so weird.

Thanks for looking at this. My use case is that I'm rendering markdown and passing it into the JSX parser. So, having special components or bindings isn't really helpful. The reason I'm using this JSX parser is so I can write markdown that includes component syntax and they get rendered into the DOM.

[Click for markdown](https://gist.githubusercontent.com/maddox/bd02464670f3a81415d53cc6439a3edb/raw/f14a1dfd96c75bb26c972046bae77b2d3be455d8/example.md)

Good lord, that was impossible to put into this issue. Writing an example of markdown in a text field that supports markdown, lol. Go ahead and click to see the raw markdown I'm writing that gets parsed into markup that is then passed into the JSX parser. That example ends up with a blank render.

**Comment by TroyAlford** [comment]
Yeah, lol. The fact that GitHub struggles with it is no surprise to me - given that it's precisely the same type of example as what we're discussing my component has trouble with. ;)

The problem is that `{ /* stuff here */ }` _is_ JSX syntax. So - the parser sees and understands the opening/closing `<code />` tag, and then it renders a string of `window.setup = () => ` and then it finds the first `{` and assumes you are about to inject a binding. When it then finds a series of statements inside that binding, it throws them away (because this component does _not_ support function binding, as it is a potential vector for XSS attacks).

I think what you want to use is the same approach outlined [in this article](https://medium.com/@jbell714/rendering-code-snippets-in-jsx-react-936746c02bca). In short - try this:

```
<code>{`
window.setup = () => {
  // pre-load sound
  sound = loadSound('https://files.tttiny.com/production/users/jon/assets/r2d2.mp3');

  // create your canvas
  createCanvas(300, 300)

  // draw a background with a color
  background("cornflowerblue")

  // write text
  fill('blue')
  textSize(32)
  textAlign(CENTER)
  text("Click for R2-D2", 0, 10, 300, 300)
}
`}</code>
```

The important part is the `{\`` and `\`}` just inside the `<code />` declaration - which tells the `JsxParser` that everything inside is a string literal. I _think_ this should resolve your issue - but I have not tested it explicitly.
