### ISSUE TITLE
Event function usage parameters no trigger

### ISSUE THREAD

**Issue by amily4555** [TroyAlford/react-jsx-parser#55]
version 1.3.1 
```jsx
<JsxParser
                        bindings={{
                            testClick: (a, b) => {
                                console.log(a, b)
                            }
                        }}
                        
                        blacklistedAttrs={[]}
                        jsx={`
                            <div onClick={testClick('a', 'b')}>test click</div>
                            <div onClick={testClick.bind('a', 'b')}>test click</div>
                        `}
  ></JsxParser>

```

how function.testClick use params ??

**Comment by TroyAlford** [comment]
Yes - I don't think that expression will work. The parser probably discards both forms, unfortunately. The parser does not make any attempt, at this time, to actually evaluate JavaScript expressions - because this is an exploitable vector for XSS Injection attacks. Instead, it simply attempts to match the expression itself with one of the bindings by name.

In other words - what you've done won't work, but the following would:
```javascript
  <JsxParser
    bindings={{ boundClick: (...args) => { console.log(...args) } }}
    blacklistedAttrs={[]}
    jsx={`<div onClick={boundClick}>Click me!</div>`}
  />
/>
```
