### ISSUE TITLE
Jest test using JsxParser component fails

### ISSUE THREAD

**Issue by swellingt0n** [TroyAlford/react-jsx-parser#60]
I am getting the following error when I try to write a jest test case that utilizes the JsxParser component.

ReferenceError: Unknown plugin "transform-react-remove-prop-types" specified in "/.../node_modules/react-jsx-parser/.babelrc" at 2, attempted to resolve relative to "/.../node_modules/react-jsx-parser"

My jest configuration is using the default transformIgnorePatterns and is not specifying a transform property.

Dependencies:
"babel-jest": "21.2.0"
"jest": "21.2.1"
"react-jsx-parser": "1.3.4"

**Comment by TroyAlford** [comment]
It sounds like your local babel is attempting to process the component's `.babelrc`. I suspect you may be importing the `JsxParser` component directly - but unsure. Either way, you should be able to resolve this fairly simply by just running `npm install --save-dev transform-react-remove-prop-types`

**Comment by TroyAlford** [comment]
That's pretty odd. The `react-jsx-parser` component doesn't use that transform. Are you using the `remove-prop-types` babel transformer?

**Comment by swellingt0n** [comment]
For some reason, the .babelrc in the node_modules/react-jsx-parser directory DOES use it. Makes no sense to me so I thought I'd see if you or any others had seen this issue.

**Comment by TroyAlford** [comment]
Try deleting your `node_modules` folder, and then run `npm install` again?

**Comment by swellingt0n** [comment]
@TroyAlford Sorry for the late response. I'll try that out as soon as I can and report back, or if it somehow fixes itself (which would be even more confusing) I'll close the issue.

**Comment by TroyAlford** [comment]
Closing this issue for the time being, as I can't reproduce and haven't heard back. :) Please feel free to respond again if this is still an issue for you.

**Comment by jeffmwells** [comment]
@TroyAlford I am getting a similar issue in the latest release (1.18.0). The issue is that the installed package does not need to include a .babelrc file since it is already transpiled and minified, but it is there in node_modules. The way to fix this is to use the `files` key in package.json to whitelist the files that get published. For now I am including the module in `transformIgnorePatterns`.

**Comment by TroyAlford** [comment]
@jeffmwells - I suspect that if your build process is running into issues with this, it's actually because you're transpiling the built files in `node_modules` rather than excluding them. If you're using `webpack` or similar, it's typical to instruct the parser not to parse things in the `node_modules` folder at all - to prevent things like this.

I don't mind creating an `.npmignore` file to exclude the babel files, or other things, if that helps - but imho this has to do with your build process, not the package itself.

Happy to take a PR if you want to submit one?
