### ISSUE TITLE
How can I input the state in the tag,

### ISSUE THREAD

**Issue by muhdammar** [TroyAlford/react-jsx-parser#67]
it not shown the state, I want it because want the code will be dynamically

````
const MyComponent = () => (
      <JsxParser
      bindings={}
        components={{ }}
        jsx={
          //textarea will onchange on this.state.form and parse the data in textarea
          this.state.form
          }
      />
    )

//Input in textarea
<div>{this.state.test}</div>
````

**Comment by TroyAlford** [comment]
I'm afraid I can't really understand what you're trying to accomplish, overall. Could you please try explaining it again?

**Comment by muhdammar** [comment]
```
import React, { Component } from 'react';
import JsxParser from 'react-jsx-parser'
import Tables from './containers/Tables/Tables';
import CommandForm from './containers/CommandForm/CommandForm';


class App extends Component {
  constructor( props ){
    super(props);
          //the state of data is in unordered list
    //and sort it by ascending alphabet in table
    this.state = {
     
    value:"",
    form : "",

    }
    
    this.handleChange = this.handleChange.bind(this);

  }

  
  handleChange(event) {
    this.setState(({form: event.target.value}));
    // event.preventDefault();
  }

  

  render() {
    const MyComponent = () => (
      <JsxParser
      allowUnknownElements= {true}
      bindings={
    }
        components={{Tables, CommandForm  }}
        jsx={
        this.state.form
          }
      />
    )




    return (
      
     
      <div className="container text-center" >
        <CommandForm 
        clicked={this.handleSubmit}
        value={this.state.form}
        changed={this.handleChange}  
        />   
      </div>
    );
  }
}

export default App;
```

**Comment by muhdammar** [comment]
this is my code

I have textarea input so when I code

<div>Hello World</div> 

it works and show the output

but

**Comment by TroyAlford** [comment]
Ok - there are several problems with how you're approaching this. The first is that you're never actually rendering the `JsxParser` component at all. I'm also a little unclear on why you're not just rendering the form itself, rather than attempting to inject it as JSX and late-parse it.

It sounds like you're wanting a `<textarea>` where you enter JSX, and then have it rendered by the component. To do so, the basic form you want is this:

```javascript
class MyComponent extends React.Component {
  state = { jsx: '' }

  constructor(props) {
    super(props)
    this.handleChange = this.handleChange.bind(this)
  }
  handleChange(event) {
    this.state.jsx = event.target.value
  }

  render() {
    return (
      <div className="my-component wrapper">
        <textarea onChange={this.handleChange} />
        <JsxParser jsx={this.state.jsx} />
      </div>
    )
  }
}
```

From there, you can start allowing other components rendered by the JSX to be special. An example might be to create a SortableList component, which renders a `UL` which has a sort-button. You'd bind it like this:

```javascript
  <JsxParser components={{ ul: SortableList }} jsx={this.state.jsx} />
```

Now, when someone enters a `UL` tag into the textarea, the JsxParser will attempt to render it by invoking your `SortableList` component, instead of a basic `UL`.

Hopefully that helps. :) I'm going to close this issue, since it's more of a Q&A, rather than a problem - but feel free to ask for more help if you need it, and I'll try to respond when I can.
