### ISSUE TITLE
Incompatibility with React 15.6.2

### ISSUE THREAD

**Issue by alsakhaev** [TroyAlford/react-jsx-parser#80]
It's impossible to use this library (v1.2.5 and above) with React 15.6.2, because this error is throwing:

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.

It seems to me that [using of <React.Fragment>](https://github.com/TroyAlford/react-jsx-parser/commit/29f39d81e68b2da74a757c7c246c4968f56d7f94) may to be a reason of it, because when i remove tags <Fragment> from sources in version 1.13.0 then it starts to work.

[Here](https://codesandbox.io/s/lry89on6xq) is the example to reproduce this problem.
If dump version to 1.2.4 or pump react version to 16.x.x then everything is works.

**Comment by alsakhaev** [comment]
As I understood, <Fragment> supporting started from 16 version of React.
Is it possible to make some checking for Fragment class existence before rendering inside parseExpression() function?
I'm sorry, the world of React is new for me...

**Comment by TroyAlford** [comment]
Checking for the `Fragment` being valid and having a fallback might be a good approach, here. The problem, I think, is that it will break the binding for special characters/emojis, iirc.

A couple suggestions:

1. If possible, use the latest version of `react` in your project. (I'm guessing this isn't possible, though, since you're trying to solve this this way)
2. Consider using `v1.2.0` instead of latest. You'll miss out on some features, but this version is already compatible with React 15.
3. Try to update your current PR so that it passes all of the unit tests. I'd love to be able to eliminate the dependency on `Fragment`, for this kind of backwards compatibility - but any change needs to pass the unit tests that are currently there to validate rendering.
4. Consider applying your patch via [patch-package](https://www.npmjs.com/package/patch-package).

If you take Option 3, you can either patch the source, then pull in the component itself as:
```
import JsxParser from 'react-jsx-parser/source/components/JsxParser'
```
Or, you can patch the built file - it's just a little uglier to do.
