### ISSUE TITLE
Incorrect output for JsxText which is falsy, but not null

### ISSUE THREAD

**Issue by lucklove** [TroyAlford/react-jsx-parser#83]
Reproduce code:
```js
jsx='<span>{0}</span>'
```
The expected result is `<span>0</span>`, but in fact it's `<span></span>`.

I think it's cause by [this](https://github.com/TroyAlford/react-jsx-parser/blob/47f7628c10c27805ef38906fe7dc66971ed2cc7c/source/components/JsxParser.js#L50)

**Comment by TroyAlford** [comment]
Yep - I suspect you're right. React doesn't output nodes which are `null` or `undefined` - but it _does_ output the number 0. This Lib is reliant on a falsy check which is too broad.

I'd be happy for a PR if you had time to submit one, and include a new unit test? Otherwise I'll try to get to this sometime soon, just not sure quite when.

**Comment by lucklove** [comment]
I'm not sure if I have time to do this since I'm busy on a lot of work these days, but if you can fix this, my team will be very grateful to your work.

**Comment by TroyAlford** [comment]
This is now resolved and published in `v1.15.1` :) Thanks for the :bug: report!
