### ISSUE TITLE
Does not render Image component

### ISSUE THREAD

**Issue by miphe** [TroyAlford/react-jsx-parser#86]
When using the JSXParser with React Native, Image components doesn't seem to render at all.

```
const markup = "<WrapperCmp><Image width={50} height={50} source={{ uri: 'https://facebook.github.io/react-native/docs/assets/favicon.png'}} /></WrapperCmp>";

<JsxParser jsx={markup} />
```

Using: v`1.16.1`

**Comment by TroyAlford** [comment]
Oh, interesting. I don't do any React Native development, at the moment - so I've never tested it with that. I'd be very happy for a PR, if you're interested in providing one, though?

**Comment by miphe** [comment]
@TroyAlford 

I'm not sure what is causing this particular problem, but using the JSXParser with `componentsOnly: true` and `renderInWrapper: false`, lets us parse JSX that is OK for React Native as well. I will see if I can come up with what could be the problem with the `<Image>`.

**Comment by miphe** [comment]
Looks like I was hasty in this report. Images renders fine with this package, the usual React Native image related quirks still applies and that's what got me.

**Comment by TroyAlford** [comment]
Awesome :) glad it's working for you, especially since it's in a way I
never knew it could! :)

**Comment by jide** [comment]
In my case I had to strip white spaces between tags and line returns, otherwise RN complains about text needing to be enclosed in Text components : 
```js
jsx.replace(/\r?\n|\r/g, '').replace(/>\s+</g, '><')
```
If it complains it means that even in react-dom there should be unwanted spaces characters inserted in the tree, and it may break some html, so this may be need a global fix at the lib level.

**Comment by TroyAlford** [comment]
Unfortunately, this kind of global fix breaks things like:

```
<p>Paragraph with <b>bold</b> <i>and</i> <u>underlined</u> text</p>
```

If we simply strip the spaces between tags, it effectively concatenates these styling tags so that there is no longer space between the words. I could envision, perhaps, having an opt-in prop, like `stripWhitespaceBetweenTags: boolean` or similar - but this is the only report I've heard of this being an issue, and it sounds like you already have a workaround.

**Comment by jide** [comment]
It's actually specific to RN since text is only allowed inside <Text> elements, and spaces are considered text. The workaround is fine for me, not asking for a change here, it's an uncommon case I guess.

That said I'm curious how React itself handles white spaces between elements when parsing JSX into createElement, since I believe it won't create text nodes between components elements, but only inside markup elements if I'm not wrong.
