### ISSUE TITLE
onClick attribute is getting removed blacklistedAttrs is set to []

### ISSUE THREAD

**Issue by zoharkazmi** [TroyAlford/react-jsx-parser#91]
I saw your documentation and tried to set blacklistedAttrs={[]}, but onClick is still being removed and it is getting rendered as 
`<div>Hello</div>`

Code:
`<JsxParser
              renderInWrapper={false}
              components={this.props.components}
              blacklistedAttrs={[]}
              onError={e => {
                /* eslint-disable no-console */
                console.log('Error in loading page');
                console.log(e);
                /* eslint-disable no-console */
              }}
              jsx={'<div onClick="console.log(\'a\')">Hello</div>'}
            />`

**Comment by zoharkazmi** [comment]
onClick is coming upto React element but not rendering it in Html. When i look at React chrome extension in developer tools i see onClick is coming after adding blacklistedAttrs={[]}
{
  "className": "poster",
  "onClick": "console.log(\'a\')"
}

but in html it is still not there so onclick is not working

**Comment by TroyAlford** [comment]
You can't run things like `console.log` inside a bound function like this, because it's a security risk. To accomplish what you're trying to do, you need to create a binding, like so:
```
<JsxParser
  bindings={{
    handleClick() { console.log('a') }
  }}
  blacklistedAttrs={[]}
  components={this.props.components}
  jsx={'<div onClick={handleClick}>Hello</div>'}
  onError={e => console.log('Error in loading page', e)}
  renderInWrapper={false}
/>
```

**Comment by zoharkazmi** [comment]
Understand, but the reasons I am using this component is my page html is dynamic which is managed in cms tool by a developer in business team. They have a developer in their team to make small functionalities like expand/collapse hide/show etc using cms itself. He uses onClick a lot, he can also define a function which will hide/show things. We handle dynamic part of page using react component like payment history table. If I have to create a binding function matching the name he used in html then it adds a code deployment dependency before he adds a new small function, which is surely not acceptable by business. Is there a way you can expose an attribute which if set to true will not remove on* attributes from any of the html tags and it will render it as it is. So if calling function exist/loaded by a file in the browser it will work otherwise it won’t

**Comment by TroyAlford** [comment]
@zoharkazmi - I understand what you're after. Unfortunately, there are 2 major problems with doing so:

1. it is a _major_ security problem. In your case, your _intended_ user is someone who you trust, making changes in a CMS - but if a hacker was able in some fashion to alter the payload of that save, you have a _terrible_ OWASP violation on your hands. Nothing would then prevent a malicious user from pushing scripts which post private information, further alter data, etc. into your system - so the easiest thing to do is disable such functionality entirely.
2. there are a number of additional types of code which this package would have to implement in order to make such a script work. We would quickly get into which syntaxes to support (ES6 style arrow functions, generators, etc) and this then becomes a rabbit-hole of on-the-fly transpilation.

In your case, you're trying to make `console.log` work. This function isn't the problem. The problem is that as soon as you open it up to browser natives, you also have access to `fetch` and other AJAX-style methods - which means malicious users can post data via dynamic scripts to 3rd party websites. That's not a can of worms I'm willing to support with this package.
